<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AspireForge.Core\AspireForge.Core.csproj" />
    <ProjectReference Include="..\AspireForge.Analyzers\AspireForge.Analyzers.csproj" />
    <ProjectReference Include="..\AspireForge.Generators\AspireForge.Generators.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>aspireforge</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
